apps/funcionarios/urls.py
from turtle import home
from unicodedata import name
from django.urls import path, include
from .views import FuncionariosList, FuncionarioEdit, FuncionarioDelete, FuncionarioNovo

urlpatterns = [
    path('', FuncionariosList.as_view(), name='list_funcionarios'),
    path('editar/<pk>', FuncionarioEdit.as_view(), name='update_funcionario'),
    path('delete/<pk>', FuncionarioDelete.as_view(), name='delete_funcionario'),
    path('novo/', FuncionarioNovo.as_view(), name='create_funcionario'),
    
]

gestao_rh/urls.py
from xml.dom.minidom import Document
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('apps.core.urls')),
    path('funcionarios/', include('apps.funcionarios.urls')),
    path('departamentos/', include('apps.departamentos.urls')),
    path('documentos/', include('apps.documentos.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('empresa/', include('apps.empresas.urls')),
    path('registro_hora_extra/', include('apps.registro_hora_extra.urls')),
    path('admin/', admin.site.urls),
  
    
]+ static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

apps/documentos/models.py
from django.db import models
from django.shortcuts import reverse

from apps.funcionarios.models import Funcionario


class Documento(models.Model):
    descricao = models.CharField(max_length=100)
    pertence = models.ForeignKey(Funcionario, on_delete=models.PROTECT)
    arquivo = models.FileField(upload_to='documentos')

    def get_absolute_url(self):
        return reverse('update_funcionario', args=[self.pertence.id])

    def __str__(self):
        return self.descricao

apps/funcionarios/models.py
from audioop import reverse
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse
from apps.departamentos.models import Departamento
from apps.empresas.models import Empresa


class Funcionario(models.Model):
    nome = models.CharField(max_length=100)
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    departamentos = models.ManyToManyField(Departamento)
    empresa = models.ForeignKey(Empresa, on_delete=models.PROTECT, null=True, blank=True)

    # class Meta:
    #     verbose_name = _("funcionario")
    #     verbose_name_plural = _("funcionarios")

    def __str__(self):
        return self.nome

    def get_absolute_url(self):
        return reverse("list_funcionarios")

apps/funcionarios/views.py
from dataclasses import field, fields
from pyexpat import model
from django.http import HttpResponse
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views.generic import ListView, UpdateView, DeleteView, CreateView
from .models import Funcionario
from django.contrib.auth.models import User


class FuncionariosList(ListView):
    model = Funcionario

    def get_queryset(self):
        empresa_logada = self.request.user.funcionario.empresa
        queryset = Funcionario.objects.filter(empresa = empresa_logada)
        return queryset    


class FuncionarioEdit(UpdateView):
    model = Funcionario
    fields = ['nome', 'departamentos']

class FuncionarioDelete(DeleteView):
    model = Funcionario
    success_url =  reverse_lazy('list_funcionarios')

    
class FuncionarioNovo(CreateView):
    model = Funcionario
    fields = ['nome', 'departamentos']

    def form_valid(self, form):
        funcionario = form.save(commit = False)
        funcionario.empresa = self.request.user.funcionario.empresa
        funcionario.user = User.objects.create(username = funcionario.nome.split(' ')[0] + funcionario.nome.split(' ')[1])
        funcionario.save()
        return super(FuncionarioNovo, self).form_valid(form)

apps/funcionarios/templates/funcionarios/funcionario_confirm_delete.html
{% extends 'base.html' %}

{% block main %}

<form method="POST">
    {% csrf_token %}
    {{form}}

    <h2> Confirmar a exclusão de {{ object_list }} </h2>
    
    <button type = "submit" class ="btn btn-danger"> Excluir </button>
</form>


{% endblock  %}

apps/funcionarios/templates/funcionarios/funcionario_form.html
{% extends 'base.html' %}  
{% load bootstrap %}
{% block main %}

{{ object.nome }} | {{ object.user }}

<form method="POST">
    {% csrf_token %}
    {{form|bootstrap}}

    

    <button type = "submit" class ="btn btn-main"> Salvar </button>
</form>

<br>
<a class="btn btn-primary btn-sm " href=" {% url 'create_document' object.id  %} " role="button"> Novo Documento </a>
<br>
{% for documento  in object.documento_set.all  %}
    
    <a href ="{{ documento.arquivo.path }}">   {{ documento }} </a> <br>


{% endfor  %}

{% endblock  %}

apps/funcionarios/templates/funcionarios/funcionario_list.html
{% extends 'base.html' %}  

{% block main %}

{% for funcionario in object_list %}

    <a href="{% url 'update_funcionario' funcionario.id  %} ">
        {{ funcionario }}
    </a> 
    <a class="btn btn-primary btn-sm " href="{% url 'delete_funcionario' funcionario.id %}" role="button"> Deletar </a>
    </br>

{% endfor %}

<a class="btn btn-primary" href="{% url 'create_funcionario' %}" role="button">Novo</a>

{% endblock  %}